### ISSUE TITLE
player state change observation doesn't seem to work in Release builds

### ISSUE THREAD

**Issue by mikeg0184** [mihai8804858/swift-chunked-audio-player#11]
I'm observing an an audioplayer's state like so:

```
      player.$currentState.sink { state in
        print(state)
        if state == .playing {
            // Do something
        }

        if state == .completed {
          // Do something else
        }
      }.store(in: &bag)
```

This work perfectly fine in Debug builds, however in a Release build it immediately stops receiving events after `initial`.

**Comment by mihai8804858** [comment]
Hi, I just tried running the example project in Release on device and `currentState` is being updated property. Can you try again from latest version? If it's still reproducible, can you try if you can replicate in the example project?

**Comment by mikeg0184** [comment]
I think it was an issue with my implementation, after some updates it no longer seems to be occurring. I'll close.
