### ISSUE TITLE
didFinishPlaying firing prematurely due to error in AudioSynchronizer.observeError

### ISSUE THREAD

**Issue by mikeg0184** [mihai8804858/swift-chunked-audio-player#12]
`AudioSynchronizer.observeError` seems to be falsely reporting an error which is triggering the `didFinishPlaying` closure in prepareSynchronizer. I say "falsely" because the error is always nil and the audio stream continues to work fine.

![image](https://github.com/user-attachments/assets/54763412-f184-41d7-9bbd-9ede25069c3d)

**Comment by mihai8804858** [comment]
Released in [1.0.6](https://github.com/mihai8804858/swift-chunked-audio-player/releases/tag/1.0.6).
