### ISSUE TITLE
Update to ReadMe -- Listening for changes

### ISSUE THREAD

**Issue by ClayGriifith** [mihai8804858/swift-chunked-audio-player#15]
Thanks so much for making swift-chunked-audio-player. I have it working in my app now with no issues at all -- the recent update fixed a weird thing I was seeing where some streamed playback stopped prematurely (I assume due to how remaining time was being monitored). **Great work.**

Unless I'm mistaken, the docs/ReadMe needs a slight update to the _Listening for Changes_ bit. I believe this now uses CurrentState, not State. 

That took me some time to troubleshoot initially. Thanks again, 

CG

**Comment by mihai8804858** [comment]
Thanks, updated README file.
