### ISSUE TITLE
No way to detect audio metering or power values of AVSampleBufferAudioRenderer

### ISSUE THREAD

**Issue by stefanteulon** [mihai8804858/swift-chunked-audio-player#4]
I'm trying to display the decibels of the playback using this method there doesn't seem to be any metering or power value options using AVSampleBufferAudioRenderer, unless I'm mistaken.

This would require a a custom function added to the playback to update the meter in real time or on a timer?

**Comment by mihai8804858** [comment]
Hi @stefanteulon, I haven't worked with this before but theoretically this should be possible by analysing the `CMSampleBuffer`s in real time using [vDSP](https://developer.apple.com/documentation/accelerate/vdsp), I'll look more into this.

**Comment by mihai8804858** [comment]
Please check this commit - https://github.com/mihai8804858/swift-chunked-audio-player/commit/be544130ed237561c0058ec8f786c7d7c267e026 

I exposed the currently playing `CMSampleBuffer` in `AudioPlayer`, and then wrote a function that converts the sample buffer data into decibels using `vDSP`, then display the decibels level based on current time. 

I can't promise though that the decibels are correctly calculated, you might want to look more into that.
