### ISSUE TITLE
Crash AudioFileStream.close

### ISSUE THREAD

**Issue by mikeg0184** [mihai8804858/swift-chunked-audio-player#7]
I havent had time to dig into the issue yet, but I'm seeing a crash when using the latest version. I'll spend some more time debugging next week and will paste a screenshot below for now. FWIW, this isn't happening on my [forked repo](https://github.com/mikeg0184/swift-chunked-audio-player).

<img width="1717" alt="Screenshot 2024-06-21 at 5 59 42 PM" src="https://github.com/mihai8804858/swift-chunked-audio-player/assets/92575/a167b413-ff89-43e1-9ac2-08789f85ab42">

**Comment by mihai8804858** [comment]
Can you try on the latest [commits](https://github.com/mihai8804858/swift-chunked-audio-player/commit/3cbb4ce57af205b5fc402fc7822cbc56cd70837c) if it's still reproducible?

**Comment by mikeg0184** [comment]
I tried on `main` and now I'm consistently getting a crash at:

![image](https://github.com/mihai8804858/swift-chunked-audio-player/assets/92575/8da49dde-a1d4-4082-8689-c1e99a62ff72)

**Comment by mihai8804858** [comment]
> I tried on `main` and now I'm consistently getting a crash at:
> 
> 
> 
> ![image](https://github.com/mihai8804858/swift-chunked-audio-player/assets/92575/8da49dde-a1d4-4082-8689-c1e99a62ff72)
> 
> 

Can you share which Xcode and iOS version are you using? Also if running on device or simulator.

**Comment by mikeg0184** [comment]
@mihai8804858 xcode 15.3 and iOS 17.5.1 on a physical iPhone 12 pro

**Comment by mikeg0184** [comment]
I spent some time looking into this and I think the issue is on my end. I was initializing the `AudioPlayer` inside an `AsyncStream` which I think is not very thread-safe. When I move the initialization outside of the AsyncStream I dont experience the crash.

**Comment by mihai8804858** [comment]
> I spent some time looking into this and I think the issue is on my end. I was initializing the `AudioPlayer` inside an `AsyncStream` which I think is not very thread-safe. When I move the initialization outside of the AsyncStream I dont experience the crash.

Thanks, I was also able to reproduce the crash on my side and I'm looking into a fix on our side as well.

**Comment by mihai8804858** [comment]
Should be fixed in [1.0.4](https://github.com/mihai8804858/swift-chunked-audio-player/releases/tag/1.0.4).
